package #(packageName);

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
#if (isGenerateChainSetter)
@SuppressWarnings({"serial", "unchecked"})
#else
@SuppressWarnings("serial")
#end
public abstract class Base#(tableMeta.camelName)Model <M extends Base#(tableMeta.camelName)Model<M>> extends Model<M> implements IBean {

#set(b = isGenerateChainSetter)
#for(cm : tableMeta.columnMetas)
	
	public #(b ? 'M' : 'void') set#(firstCharToUpperCase(cm.javaName))(#(cm.javaType) #(cm.javaName)) {
		set("#(cm.name)", #(cm.javaName));
		#if (b)
		return (M)this;
		#end
	}
	
	#set(getterOfModel = getterTypeMap.get(cm.javaType))
	#if (isBlank(getterOfModel))
		#set(getterOfModel = 'get')
	#end
	public #(cm.javaType) get#(firstCharToUpperCase(cm.javaName))() {
		return #(getterOfModel)("#(cm.name)");
	}

#end
}

