package #(packageName);

import #(baseModelPackageName);

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class #(tableMeta.camelName) extends #(baseModelName)<#(tableMeta.camelName)> {
	#if (isGenerateDaoInModel)
	public static final #(tableMeta.camelName) dao = new #(tableMeta.camelName)().dao();
	#else
	
	#end
}

